name: Docker build and push Staging

concurrency:
  group: docker-build-staging
  cancel-in-progress: false


on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - ".github/workflows/docker-build-staging.yml"
      - ".github/workflows/docker-deploy-staging.yml"
      - ".github/workflows/docker-sbom-staging.yml"

env: 
  AWS_REGION: ca-central-1
  REGISTRY_PREFIX: ${{ vars.STAGING_AWS_ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com
  GITHUB_SHA: ${{ github.sha }}

permissions: {}
  
jobs:
  docker-push:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        image:
          - alarms-slack
          - idp
          - idp-cleanup-users
          - idp-event-exporter
    
    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
        DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
        DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
        DNS_PROXY_WILDCARDGREEDY: "true"
  
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
      id: changes
      with:
        filters: |
          docker:
            - './docker/${{ matrix.image }}/**'

    - name: Exit if no changes
      if: steps.changes.outputs.docker == 'false'
      run: exit 0

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
        role-to-assume: arn:aws:iam::${{ vars.STAGING_AWS_ACCOUNT_ID }}:role/platform-unified-accounts-docker-push
        role-session-name: PushContainer
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6 
  
    - name: Build and push image
      run: |
        docker buildx build \
          --push \
          --provenance=false \
          --platform linux/arm64 \
          --tag "$REGISTRY_PREFIX/${{ matrix.image }}:sha-$GITHUB_SHA" \
          --file ./docker/${{ matrix.image }}/Dockerfile \
          ./docker/${{ matrix.image }}

  docker-deploy:
    permissions:
      id-token: write
    needs: docker-push
    uses: ./.github/workflows/docker-deploy-staging.yml
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

  docker-sbom:
    permissions:
      contents: write
    needs: docker-push
    uses: ./.github/workflows/docker-sbom-staging.yml
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

  workflow-failure:
    needs: [docker-push, docker-deploy]
    if: failure()
    uses: ./.github/workflows/workflow-failure.yml
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAGING_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}
