name: PR review get env vars

on:
  push:
    branches:
      - main
    paths:
      - "terraform/aws/**"
      - "terraform/env/**"
      - ".github/workflows/pr-review-get-vars.yml"
  workflow_dispatch:

env:
  AWS_REGION: ca-central-1

permissions:
  id-token: write
  contents: read

jobs:
  pr-review-get-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{ vars.STAGING_AWS_ACCOUNT_ID }}:role/platform-unified-accounts-pr-review-get-vars
          role-session-name: PRReviewGetEnvVars
          aws-region: ${{ env.AWS_REGION }}

      - name: Get environment variables
        env:
          CLUSTER_NAME: idp
          SERVICE_NAME: idp-login
        run: |
          .github/workflows/scripts/pr-review-get-vars.sh "$CLUSTER_NAME" "$SERVICE_NAME" > /dev/null 2>&1
